# Generated by Django 5.1.2 on 2024-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('tutor', 'Tutor'), ('student', 'Student')], default='student', max_length=7),
        ),
    ]
