# Generated by Django 5.1.2 on 2024-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='days',
            field=models.JSONField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (60, '60 min '), (90, '90 min'), (120, '120 min')]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='knowledge_area',
            field=models.CharField(choices=[('c++', 'C++'), ('scala', 'Scala'), ('java', 'Java'), ('python', 'Python'), ('ruby', 'Ruby')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='term',
            field=models.CharField(choices=[('sept-dec', 'September - December'), ('jan-april', 'January - April'), ('may-july', 'May - July')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='venue_preference',
            field=models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite')], max_length=100),
        ),
    ]
