# Generated by Django 5.1.2 on 2024-12-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='meeting',
            name='time_of_day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
