# Generated by Django 5.1.2 on 2024-11-24 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_lessonrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_area', models.CharField(choices=[('c++', 'C++'), ('scala', 'Scala'), ('java', 'Java'), ('python', 'Python'), ('ruby', 'Ruby')], max_length=50)),
                ('term', models.CharField(max_length=50)),
                ('frequency', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('days', models.JSONField()),
                ('venue_preference', models.CharField(max_length=100)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='LessonRequest',
        ),
    ]
