# Generated by Django 5.1.2 on 2024-12-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_meeting_days_meeting_time_of_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='days',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='mon', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=20),
        ),
    ]
