# Generated by Django 5.1.2 on 2024-11-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_user_user_type'),
        ('tutorials', '0003_lesson_delete_lessonrequest'),
    ]

    operations = [
    ]
