# Generated by Django 5.1.2 on 2024-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_merge_20241125_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='knowledge_area',
            field=models.CharField(max_length=50),
        ),
    ]
